In [1]:
import pandas as pd

In [2]:
path_cartoes = r'E:\Analise Brasileirao\Data\Raw\campcartoes.csv'
path_estatisticas = r'E:\Analise Brasileirao\Data\Raw\campestatisticas.csv'
path_campfull = r'E:\Analise Brasileirao\Data\Raw\campfull.csv'

In [3]:
df_cartoes = pd.read_csv(path_cartoes, encoding="UTF-8", sep=",")
df_estatisticas = pd.read_csv(path_estatisticas, encoding="UTF-8", sep=",")
df_campfull = pd.read_csv(path_campfull, encoding="UTF-8", sep=",")

In [4]:
df_cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinicius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andres D'Alessandro,10.0,Meio-campo,72

In [5]:
df_cartoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 20953 entries, 0 to 20952
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   partida_id  20953 non-null  int64
 1   rodata      20953 non-null  int64
 2   clube       20953 non-null  str
 3   cartao      20953 non-null  str
 4   atleta      20947 non-null  str
 5   num_camisa  20567 non-null  float64
 6   posicao     19755 non-null  str
 7   minuto      20953 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.3 MB

In [6]:
df_cartoes['num_camisa'] = df_cartoes['num_camisa'].astype('Int64')

In [7]:
#Setando tabela somente de 2020 para frente
df_cartoes = df_cartoes[df_cartoes['partida_id'] >= 6888]

df_cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
11201,6888,1,Sport,Amarelo,Elton Rodrigues Brandao,19,Atacante,68
11202,6888,1,Sport,Amarelo,Adryelson,34,Zagueiro,46
11203,6888,1,Ceara,Amarelo,Samuel Xavier,22,Zagueiro,48
11204,6888,1,Sport,Amarelo,Rafael,41,Meio-campo,54
11205,6888,1,Ceara,Amarelo,Fernando Sobral,88,Meio-campo,55

In [8]:
#Verificando se existem valores nulos
df_cartoes.isnull().sum()

partida_id    0
rodata        0
clube         0
cartao        0
atleta        4
num_camisa    0
posicao       0
minuto        0
dtype: int64

In [9]:
#Exibindo as linhas onde o nome do atleta é nulo
df_cartoes[df_cartoes['atleta'].isnull()]

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
12363,7124,24,Internacional,Amarelo,NaN,14,Zagueiro,58
13106,7291,3,Internacional,Vermelho,NaN,14,Zagueiro,52
13172,7309,5,Internacional,Amarelo,NaN,14,Zagueiro,65
13279,7332,7,Internacional,Amarelo,NaN,14,Zagueiro,37

In [10]:
#Removendo as linhas onde o nome do atleta é nulo - pois sao apenas 4 linhas, e nao tem como recuperar essa informacao
df_cartoes = df_cartoes.dropna(subset=['atleta'])
df_cartoes.isnull().sum()

partida_id    0
rodata        0
clube         0
cartao        0
atleta        0
num_camisa    0
posicao       0
minuto        0
dtype: int64

In [11]:
df_estatisticas.head()

#Setando tabela somente de 2020 para frente
df_estatisticas = df_estatisticas[df_estatisticas['partida_id'] >= 6888]

In [12]:
df_estatisticas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
13770,6888,1,Ceara,11,5,60%,487,82%,18,3,0,0,4
13771,6888,1,Sport,9,3,40%,324,77%,15,3,0,3,2
13776,6890,1,Flamengo,17,2,63%,525,80%,12,3,0,2,9
13777,6890,1,Atletico-MG,10,4,37%,321,71%,24,2,0,3,2
13778,6889,1,Santos,10,4,54%,444,81%,10,0,0,4,4

In [13]:
df_estatisticas.info()

<class 'pandas.DataFrame'>
Index: 4556 entries, 13770 to 18329
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   partida_id       4556 non-null   int64
 1   rodata           4556 non-null   int64
 2   clube            4556 non-null   str
 3   chutes           4556 non-null   int64
 4   chutes_no_alvo   4556 non-null   int64
 5   posse_de_bola    3782 non-null   str
 6   passes           4556 non-null   int64
 7   precisao_passes  3786 non-null   str
 8   faltas           4556 non-null   int64
 9   cartao_amarelo   4556 non-null   int64
 10  cartao_vermelho  4556 non-null   int64
 11  impedimentos     4556 non-null   int64
 12  escanteios       4556 non-null   int64
dtypes: int64(10), str(3)
memory usage: 498.3 KB

In [14]:
#Recategorizando colunas posse de bola e precisao de faltas
# Remove o % e converte pra float
df_estatisticas['posse_de_bola'] = df_estatisticas['posse_de_bola'].str.replace('%', '').astype('Int64')
df_estatisticas['precisao_passes'] = df_estatisticas['precisao_passes'].str.replace('%', '').astype('Int64')

In [15]:
#Verificando se existem valores nulos
df_estatisticas.isnull().sum()

partida_id           0
rodata               0
clube                0
chutes               0
chutes_no_alvo       0
posse_de_bola      774
passes               0
precisao_passes    770
faltas               0
cartao_amarelo       0
cartao_vermelho      0
impedimentos         0
escanteios           0
dtype: int64

In [16]:
#Verificando as linhas onde há valor nulo
df_estatisticas[df_estatisticas['posse_de_bola'].isnull()]

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
14006,7015,13,Atletico-MG,0,0,<NA>,0,<NA>,0,0,0,0,0
14007,7015,13,Vasco,0,0,<NA>,0,<NA>,0,0,0,0,0
16810,8406,1,Bahia,0,0,<NA>,0,<NA>,0,0,0,0,0
16811,8406,1,Internacional,0,0,<NA>,0,<NA>,0,0,0,0,0
16812,8407,1,Juventude,0,0,<NA>,0,<NA>,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18077,9047,27,Atletico-MG,4,1,<NA>,537,94,14,4,0,2,2
18186,9097,32,Vitoria,12,3,<NA>,231,88,14,3,0,1,4
18187,9097,32,Internacional,8,4,<NA>,298,91,21,4,0,2,4
18200,9104,32,Ceara,11,3,<NA>,374,90,18,3,0,1,5
18201,9104,32,Fortaleza,6,4,<NA>,212,83,11,3,0,0,4

In [17]:
#Como são muitoas linhas, e não tem como recuperar essa informação, vamos preencher com a média da posse de bola de cada time

#Calculando a média da posse de bola por time
media_posse_de_bola = df_estatisticas.groupby('clube')['posse_de_bola'].mean().round(0)

#Preenchendo os valores nulos com a média da posse de bola do time correspondente
for clube, media in media_posse_de_bola.items():
    df_estatisticas.loc[(df_estatisticas['clube'] == clube) & (df_estatisticas['posse_de_bola'].isnull()), 'posse_de_bola'] = media

In [18]:
#Como são muitoas linhas, e não tem como recuperar essa informação, vamos preencher com a média da posse de bola de cada time
media_posse_de_bola = df_estatisticas.groupby('clube')['precisao_passes'].mean().round(0)
for clube, media in media_posse_de_bola.items():
    df_estatisticas.loc[(df_estatisticas['clube'] == clube) & (df_estatisticas['precisao_passes'].isnull()), 'precisao_passes'] = media

In [19]:
df_estatisticas.isnull().sum()

partida_id          0
rodata              0
clube               0
chutes              0
chutes_no_alvo      0
posse_de_bola      38
passes              0
precisao_passes    38
faltas              0
cartao_amarelo      0
cartao_vermelho     0
impedimentos        0
escanteios          0
dtype: int64

In [20]:
#retirando restante de valores nulos

df_estatisticas = df_estatisticas.dropna()

In [21]:
df_estatisticas.isnull().sum()

partida_id         0
rodata             0
clube              0
chutes             0
chutes_no_alvo     0
posse_de_bola      0
passes             0
precisao_passes    0
faltas             0
cartao_amarelo     0
cartao_vermelho    0
impedimentos       0
escanteios         0
dtype: int64

In [22]:
df_estatisticas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
13770,6888,1,Ceara,11,5,60,487,82,18,3,0,0,4
13771,6888,1,Sport,9,3,40,324,77,15,3,0,3,2
13776,6890,1,Flamengo,17,2,63,525,80,12,3,0,2,9
13777,6890,1,Atletico-MG,10,4,37,321,71,24,2,0,3,2
13778,6889,1,Santos,10,4,54,444,81,10,0,0,4,4

In [23]:
#------------------------------------------------------

In [24]:
df_campfull.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [25]:
df_campfull.info()

<class 'pandas.DataFrame'>
RangeIndex: 9165 entries, 0 to 9164
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  9165 non-null   int64
 1   rodata              9165 non-null   int64
 2   data                9165 non-null   str
 3   hora                9165 non-null   str
 4   mandante            9165 non-null   str
 5   visitante           9165 non-null   str
 6   formacao_mandante   4190 non-null   str
 7   formacao_visitante  4190 non-null   str
 8   tecnico_mandante    4555 non-null   str
 9   tecnico_visitante   4555 non-null   str
 10  vencedor            9165 non-null   str
 11  arena               9165 non-null   str
 12  mandante_Placar     9165 non-null   int64
 13  visitante_Placar    9165 non-null   int64
 14  mandante_Estado     9165 non-null   str
 15  visitante_Estado    9165 non-null   str
 16  arrecadacao         380 non-null    float64
dtypes: float64(1), int64(4), str(12)
memory usage: 1.2 MB

In [26]:
#Setando categoria data para date

#Alterando / por - para padronizar a data
df_campfull['data'] = df_campfull['data'].str.replace('/', '-')
df_campfull['data'] = pd.to_datetime(df_campfull['data'], format='%d-%m-%Y')

In [27]:
#Setando dataset somente de 2020 para frente
df_campfull = df_campfull[df_campfull['ID'] >= 6888]

df_campfull.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
6885,6888,1,2020-08-08,10:40,Sport,Ceara,4-2-3-1,4-2-3-1,D. Pollo Barioni,A. Ferreira,Sport,Adelmar da Costa Carvalho,3,2,PE,CE,NaN
6888,6890,1,2020-08-09,16:00,Flamengo,Atletico-MG,4-2-3-1,3-5-2,D. Torrent Font,J. Sampaoli Moya,Atletico-MG,Maracanã,0,1,RJ,MG,NaN
6889,6889,1,2020-08-09,16:02,Santos,Bragantino,4-3-3,4-2-3-1,A. Stival,F. de Oliveira Conceição,-,Estádio Urbano Caldeira,1,1,SP,SP,NaN
6890,6891,1,2020-08-09,19:00,Gremio,Fluminense,4-2-3-1,4-3-3,Renato Gaúcho,O. Hellmann,Gremio,Arena do Grêmio,1,0,RS,RJ,NaN
6891,6896,2,2020-08-12,09:43,Athletico-PR,Goias,4-3-3,4-4-2,D. Silvestre Júnior,N. da Silveira Júnior,Athletico-PR,Estádio Joaquim Américo Guimarães,2,1,PR,GO,NaN

In [35]:
df_campfull.isnull().sum()

ID                    0
rodata                0
data                  0
hora                  0
mandante              0
visitante             0
formacao_mandante     0
formacao_visitante    0
tecnico_mandante      0
tecnico_visitante     0
vencedor              0
arena                 0
mandante_Placar       0
visitante_Placar      0
mandante_Estado       0
visitante_Estado      0
dtype: int64

In [31]:
#tirando coluna arrecadacao, pois tem muitos valores nulos e nao tem como recuperar essa informacao
df_campfull = df_campfull.drop(columns=['arrecadacao'])

In [34]:
#Preenchendo valores nulos da coluna estadio com respectivos valores
df_campfull['formacao_mandante'] = df_campfull['formacao_mandante'].fillna('4-5-1')
df_campfull['formacao_visitante'] = df_campfull['formacao_visitante'].fillna('3-5-2')

In [37]:
#Mandando respectivos datasets para processed
df_cartoes.to_csv(r'E:\Analise Brasileirao\Data\Processed\campcartoes.csv', index=False, encoding='UTF-8', sep=',')
df_estatisticas.to_csv(r'E:\Analise Brasileirao\Data\Processed\campestatisticas.csv', index=False, encoding='UTF-8', sep=',')
df_campfull.to_csv(r'E:\Analise Brasileirao\Data\Processed\campfull.csv', index=False, encoding='UTF-8', sep=',')