In [47]:
import pandas as pd

In [48]:
path_campcartoes = r'E:\Analise Brasileirao\Data\Processed\campcartoes.csv'
path_campestatistica = r'E:\Analise Brasileirao\Data\Processed\campestatisticas.csv'
path_campfull = r'E:\Analise Brasileirao\Data\Processed\campfull.csv'

In [49]:
df_campcartoes = pd.read_csv(path_campcartoes, sep=',', encoding='utf-8')
df_campestatistica = pd.read_csv(path_campestatistica, sep=',', encoding='utf-8')
df_campfull = pd.read_csv(path_campfull, sep=',', encoding='utf-8')

In [50]:
df_campestatistica.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,6888,1,Ceara,11,5,60,487,82,18,3,0,0,4
1,6888,1,Sport,9,3,40,324,77,15,3,0,3,2
2,6890,1,Flamengo,17,2,63,525,80,12,3,0,2,9
3,6890,1,Atletico-MG,10,4,37,321,71,24,2,0,3,2
4,6889,1,Santos,10,4,54,444,81,10,0,0,4,4

In [51]:
df_campfull.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,6888,1,2020-08-08,10:40,Sport,Ceara,4-2-3-1,4-2-3-1,D. Pollo Barioni,A. Ferreira,Sport,Adelmar da Costa Carvalho,3,2,PE,CE
1,6890,1,2020-08-09,16:00,Flamengo,Atletico-MG,4-2-3-1,3-5-2,D. Torrent Font,J. Sampaoli Moya,Atletico-MG,Maracanã,0,1,RJ,MG
2,6889,1,2020-08-09,16:02,Santos,Bragantino,4-3-3,4-2-3-1,A. Stival,F. de Oliveira Conceição,-,Estádio Urbano Caldeira,1,1,SP,SP
3,6891,1,2020-08-09,19:00,Gremio,Fluminense,4-2-3-1,4-3-3,Renato Gaúcho,O. Hellmann,Gremio,Arena do Grêmio,1,0,RS,RJ
4,6896,2,2020-08-12,09:43,Athletico-PR,Goias,4-3-3,4-4-2,D. Silvestre Júnior,N. da Silveira Júnior,Athletico-PR,Estádio Joaquim Américo Guimarães,2,1,PR,GO

In [52]:
df_campcartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,6888,1,Sport,Amarelo,Elton Rodrigues Brandao,19,Atacante,68
1,6888,1,Sport,Amarelo,Adryelson,34,Zagueiro,46
2,6888,1,Ceara,Amarelo,Samuel Xavier,22,Zagueiro,48
3,6888,1,Sport,Amarelo,Rafael,41,Meio-campo,54
4,6888,1,Ceara,Amarelo,Fernando Sobral,88,Meio-campo,55

In [53]:
df_campcartoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 9735 entries, 0 to 9734
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   partida_id  9735 non-null   int64
 1   rodata      9735 non-null   int64
 2   clube       9735 non-null   str
 3   cartao      9735 non-null   str
 4   atleta      9735 non-null   str
 5   num_camisa  9735 non-null   int64
 6   posicao     9735 non-null   str
 7   minuto      9735 non-null   str
dtypes: int64(3), str(5)
memory usage: 608.6 KB

In [54]:
#Agrupando informações por partida

df_campcartoes.groupby(['partida_id', 'cartao'])['cartao'].count()

partida_id  cartao
6888        Amarelo     6
6889        Amarelo     1
6890        Amarelo     5
6891        Amarelo     5
6892        Amarelo     2
                       ..
8781        Amarelo     6
8783        Amarelo     1
8784        Amarelo     7
8785        Amarelo     5
            Vermelho    2
Name: cartao, Length: 2299, dtype: int64

In [55]:
#Montando um dataframe com o número de cartões por partida

df_cartoes_partida = df_campcartoes.groupby(['partida_id', 'clube', 'cartao'])['cartao'].count().unstack(fill_value=0).reset_index()
df_cartoes_partida.head()

cartao  partida_id        clube  Amarelo  Vermelho
0             6888        Ceara        3         0
1             6888        Sport        3         0
2             6889   Bragantino        1         0
3             6890  Atletico-MG        2         0
4             6890     Flamengo        3         0

In [56]:
df_campestatistica.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,6888,1,Ceara,11,5,60,487,82,18,3,0,0,4
1,6888,1,Sport,9,3,40,324,77,15,3,0,3,2
2,6890,1,Flamengo,17,2,63,525,80,12,3,0,2,9
3,6890,1,Atletico-MG,10,4,37,321,71,24,2,0,3,2
4,6889,1,Santos,10,4,54,444,81,10,0,0,4,4

In [57]:
# --- IGNORE ---

In [58]:
#Juntando os dataframes para fazer a tabela fato

# Colunas escolhidas: partida_id | rodata | ano | data | arena | clube | condicao | adversario | vencedor | resultado | gols_marcados | gols_sofridos | saldo_gols | aproveitamento |
# formacao_mandante | formacao_visitante | chutes | chutes_no_alvo | precisao_chutes | posse_de_bola | passes | precisao_passes | faltas | impedimentos | escanteios | total_amarelos |
# total_vermelhos | mandante_Estado | visitante_Estado

In [59]:
#Realizando o merge dos dataframes para criar a tabela fato
df_campfull_limpo = df_campfull.drop(columns=['rodata'])

df_fato = df_campestatistica \
    .merge(df_campfull_limpo, left_on='partida_id', right_on='ID', how='left') \
    .merge(df_cartoes_partida, on=['partida_id', 'clube'], how='left')
df_fato.columns

Index(['partida_id', 'rodata', 'clube', 'chutes', 'chutes_no_alvo',
       'posse_de_bola', 'passes', 'precisao_passes', 'faltas',
       'cartao_amarelo', 'cartao_vermelho', 'impedimentos', 'escanteios', 'ID',
       'data', 'hora', 'mandante', 'visitante', 'formacao_mandante',
       'formacao_visitante', 'tecnico_mandante', 'tecnico_visitante',
       'vencedor', 'arena', 'mandante_Placar', 'visitante_Placar',
       'mandante_Estado', 'visitante_Estado', 'Amarelo', 'Vermelho'],
      dtype='str')

In [60]:
#Mantendo apenas as colunas escolhidas para a análise
colunas_para_manter = ['partida_id', 'rodata', 'data', 'arena', 'clube', 'vencedor', 'visitante',
                        'chutes', 'chutes_no_alvo', 'posse_de_bola', 'passes', 'precisao_passes', 'faltas', 'impedimentos', 'escanteios', 'Amarelo',
                        'Vermelho', 'mandante_Placar', 'visitante_Placar']

df_fato = df_fato[colunas_para_manter]
df_fato.head()

,partida_id,rodata,data,arena,clube,vencedor,visitante,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,impedimentos,escanteios,Amarelo,Vermelho,mandante_Placar,visitante_Placar
0,6888,1,2020-08-08,Adelmar da Costa Carvalho,Ceara,Sport,Ceara,11,5,60,487,82,18,0,4,3.0,0.0,3,2
1,6888,1,2020-08-08,Adelmar da Costa Carvalho,Sport,Sport,Ceara,9,3,40,324,77,15,3,2,3.0,0.0,3,2
2,6890,1,2020-08-09,Maracanã,Flamengo,Atletico-MG,Atletico-MG,17,2,63,525,80,12,2,9,3.0,0.0,0,1
3,6890,1,2020-08-09,Maracanã,Atletico-MG,Atletico-MG,Atletico-MG,10,4,37,321,71,24,3,2,2.0,0.0,0,1
4,6889,1,2020-08-09,Estádio Urbano Caldeira,Santos,-,Bragantino,10,4,54,444,81,10,4,4,NaN,NaN,1,1

In [62]:
#categorizando as colunas

df_fato.info()

<class 'pandas.DataFrame'>
RangeIndex: 4518 entries, 0 to 4517
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   partida_id        4518 non-null   int64
 1   rodata            4518 non-null   int64
 2   data              4518 non-null   str
 3   arena             4518 non-null   str
 4   clube             4518 non-null   str
 5   vencedor          4518 non-null   str
 6   visitante         4518 non-null   str
 7   chutes            4518 non-null   int64
 8   chutes_no_alvo    4518 non-null   int64
 9   posse_de_bola     4518 non-null   int64
 10  passes            4518 non-null   int64
 11  precisao_passes   4518 non-null   int64
 12  faltas            4518 non-null   int64
 13  impedimentos      4518 non-null   int64
 14  escanteios        4518 non-null   int64
 15  Amarelo           3485 non-null   float64
 16  Vermelho          3485 non-null   float64
 17  mandante_Placar   4518 non-null   int64
 18  visitante_Placar  4518 non-null   int64
dtypes: float64(2), int64(12), str(5)
memory usage: 670.8 KB

In [64]:
df_fato['data'] = df_fato['data'].astype('datetime64[ns]')
df_fato['Amarelo'] = df_fato['Amarelo'].astype('Int64')
df_fato['Vermelho'] = df_fato['Vermelho'].astype('Int64')

In [ ]:
#Feature engineering: Criando colunas de  ano, saldo de gols, resultado, condiçao, aproveitamento, precisaod de chutes, flag_expulsao

df_fato['ano'] = pd.to_datetime(df_fato['data']).dt.year
df_fato['saldo_de_gols'] = df_fato['mandante_Placar'] - df_fato['visitante_Placar']
df